# Generated by Django 4.2.2 on 2023-07-12 10:09

from django.db import migrations, models
import django.db.models.deletion
import utils.file_dir
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=256)),
                ('candidate_description', models.CharField(blank=True, max_length=4096, null=True)),
                ('candidate_profileImage', models.ImageField(blank=True, upload_to=utils.file_dir.Candidate_Profile_Images, validators=[utils.validators.validate_image])),
                ('encoder_ID', models.CharField(blank=True, max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=256)),
                ('category_description', models.CharField(blank=True, max_length=4096, null=True)),
                ('category_coverImage', models.ImageField(blank=True, upload_to=utils.file_dir.Category_Profile_Images, validators=[utils.validators.validate_image])),
                ('encoder_ID', models.CharField(blank=True, max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.candidatemodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.categorymodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='candidatemodel',
            name='category',
            field=models.ManyToManyField(to='vote.categorymodel'),
        ),
    ]
