# Generated by Django 4.2.2 on 2023-07-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_top_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='finger_print',
            field=models.CharField(default='finger_print'),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='ipv4',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
