name: Trigger auto deployment for leza-award-backend-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/leza-award-backend-api-AutoDeployTrigger-5e51c9a9-be2f-4699-a604-605069d346dd.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LEZAAWARDBACKENDAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: lezacontainerregistery.azurecr.io
          registryUsername: ${{ secrets.LEZAAWARDBACKENDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LEZAAWARDBACKENDAPI_REGISTRY_PASSWORD }}
          containerAppName: leza-award-backend-api
          resourceGroup: LezaAwardDevelopmentResourceGroup
          imageToBuild: lezacontainerregistery.azurecr.io/leza-award-backend-api:${{ github.sha }}
          dockerfilePath: Dockerfile

     

